=== Vict0or/DAM-Primero-ProgJava/Tema 05 Aplicacion Estrc Almacenmto/src/Discos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="CD">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CD" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Titulo" type="xs:string" />
                            <xs:element name="Artista" type="xs:string" />
                            <xs:element name="Origen" type="xs:string" />
                            <xs:element name="Precio" type="xs:string" />
                            <xs:element name="AÃ±o" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Vict0or/DAM-Primero-ProgJava/Tema 05 Aplicacion Estrc Almacenmto/src/Discos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Discos.xsd">
    <CD>
        <Titulo>Back in Black</Titulo>
        <Artista>Victor</Artista>
        <Origen>Espa¤a</Origen>
        <Precio>29.95</Precio>
        <Año>1999</Año>
    </CD>
    <CD>
        <Titulo>Aerosmith</Titulo>
        <Artista>Bon Jovi</Artista>
        <Origen>England</Origen>
        <Precio>35.0</Precio>
        <Año>2023</Año>
    </CD>
</CD>
